---
services:
  foundry:
    image: felddy/foundryvtt:13
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ~/foundry/data:/data
      - ../:/data/Data/modules/tor2e-theme
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD:-test}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME:-test}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY:-test}
      #- FOUNDRY_VERSION=${FOUNDRY_VERSION:-13.342}
    ports:
      - "30000:30000"
