name: Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - 'version.txt'

jobs:
  create_foundry_release:
    runs-on: ubuntu-latest
    name: Foundry Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GitHub Release
        id: github-release
        uses: foundryvtt-dcc/foundry-release-action@main
        with:
          actionToken: ${{ secrets.GITHUB_TOKEN }}
          manifestFileName: 'module.json'
          manifestProtectedTrue: true